import type { Metadata } from 'next';
import '@/app/globals.css';

import { Providers } from '@/app/Providers';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function ResturantLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main>{children}</main>;
}
