import type { Metadata } from 'next';
import '@/app/globals.css';
import { Providers } from '../Providers';
import AppLayout from '@/components/appLayout';
export const metadata: Metadata = {
  title: 'Dey go',
  description: 'Generated by create next app',
};

export default function OuterLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <AppLayout>{children}</AppLayout>;
}
