import type { Metadata } from 'next';
import '@/app/globals.css';
import { Providers } from '../Providers';
import AppLayout from '@/components/appLayout';
import LoginLayout from '@/components/loginLayout';
export const metadata: Metadata = {
  title: 'Dey go',
  description: 'Generated by create next app',
};

export default function Login({
  children,
}: {
  children: React.ReactNode;
}) {
  return <LoginLayout>{children}</LoginLayout>;
}
