import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './Providers';
import Header from '@/components/Header';
import SideBar from '@/components/Sidebar';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body>
        <Providers>
          <>
            <Header />
            <main>
              <SideBar />
              <div className="hidden md:block md:ml-72">{children}</div>
            </main>
          </>
        </Providers>
      </body>
    </html>
  );
}
