import type { Metadata } from 'next';
import '@/app/globals.css';
import AppLayout from '@/components/appLayout';
import { Providers } from './Providers';
export const metadata: Metadata = {
  title: 'Dey go',
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: '/favicon.svg' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light" suppressHydrationWarning={true}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
