import type { Metadata } from 'next';
import '@/app/globals.css';
import { Providers } from './Providers';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import ReactQueryProvider from '@/utils/queryProvider';

export const metadata: Metadata = {
  title: 'Dey go',
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: '/favicon.svg' }],
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light" suppressHydrationWarning={true}>
      <body>
        <ReactQueryProvider>
          <Providers>{children}</Providers>
          <ReactQueryDevtools initialIsOpen={false} />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
